### ISSUE TITLE
Review namelist xml files and modify appropriately

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cism-wrapper#9]
The namelist definition and defaults files (in https://github.com/ESCOMP/cism-wrapper/blob/master/bld/namelist_files) need to be reviewed prior to the release to make sure:

- All variables that we want people to be able to modify in a CESM run are listed in the namelist_definition file

- Options for each variable are documented correctly

- Defaults are correct

**Comment by billsacks** [comment]
@gunterl and @whlipscomb We've talked about this verbally, but I wanted to document the need for this at some point in the next month or so.

**Comment by billsacks** [comment]
We still have a few weeks, but I just wanted to note: this needs to be done in time for the May 11 code freeze.

**Comment by whlipscomb** [comment]
@billsacks, Thanks for the heads-up.  @gunterl and I will add this to our list of tasks to be done before May 11 (and in time for you to review and test).

**Comment by gunterl** [comment]
@billsacks, @whlipscomb  and I just had a discussion about the history variables. Here is what we decided: just to be clear, here I am only referring to the "cesm_history_vars" involving CISM2 (the one for CISM1 remain unchanged).
- When CISM is set to "no evolve" the velocity and temperature solvers are not called and we believe that the following list is enough: smb, artm, thk, usurf, topg 
@billsacks do you know if any other fields are necessary in order to do SMB downscaling? If so please add whatever is needed.
- When CISM is set to "evolve" then we think that the list in place is good but we would like to add this field: calving_thck. 

@whlipscomb do we need to go through the default parameters list as well or is this good to go?

Thanks

**Comment by whlipscomb** [comment]
@gunterl, Thanks for working through this list.  I'd like to do some more Greenland tests before settling on the final default options and parameters.  I'll keep you and @billsacks posted.

**Comment by billsacks** [comment]
Thanks, @gunterl . I'll probably just include those changes with any other changes needed to the xml files.

For any other changes needed, feel free to create a branch and make changes directly there – that will probably be easier than describing the changes (which risks miscommunications).

**Comment by billsacks** [comment]
Note to self: Also add calving_thck to `cime_config/usermods_dirs/cmip6_evolving_icesheet/user_nl_cism`.

**Comment by billsacks** [comment]
I have addressed the above output field requests in 697e71807ee3a4c50f16f426533c21e86c828183

**Comment by billsacks** [comment]
Fixed by #13 (96bc5f22b64c54b6e7ed1bef3a9001a421263563)
